# RoleBindings.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader-binding
  namespace: default
subjects:
- kind: User
  name: nom@entreprise.com
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-manager-binding
  namespace: default
subjects:
- kind: User
  name: ju****@**************.com
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: secret-manager
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admin-binding-alice  # Nom du ClusterRoleBinding
subjects:
- kind: User                         # Type de sujet (ici, un utilisateur)
  name: g*****@**************.com    # Nom de l'utilisateur
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole                  # Type de rôle (ici, un ClusterRole)
  name: cluster-admin                # Nom du ClusterRole référencé
  apiGroup: rbac.authorization.k8s.io
